image: circleci/android:api-28

options:
  size: 2x

pipelines:
  default:
    - step:
        caches:
          - gradle
        script:
          - bash ./license.sh
          - ./gradlew assemble --stacktrace